"""Core Pydantic schemas — compatibility facade.

All schema definitions now live in feature-scoped sub-modules under
``core/schemas/``.  This ``__init__`` re-exports every public name so
that existing ``from core.schemas import X`` statements continue to
work without modification.

The sub-modules are:
  assistant, chat, graph, knowledge_base, practice, quizzes, research, workspaces
"""

from __future__ import annotations

# ── Re-exports from sub-modules ──────────────────────────────────────

from core.schemas.assistant import (  # noqa: F401
    ActionCTA,
    AnswerParts,
    AssessmentCard,
    AssistantDraft,
    AssistantResponseEnvelope,
    AssistantResponseKind,
    CITATION_LABEL_FROM_NOTES,
    CITATION_LABEL_GENERAL_CONTEXT,
    Citation,
    CitationLabel,
    ConceptSwitchSuggestion,
    ConversationMeta,
    EvidenceItem,
    EvidenceSourceType,
    GenerationTrace,
    GroundingMode,
    HierarchyNode,
    ReadinessSnapshotResponse,
    ReadinessTopicState,
    RefusalReason,
    ResponseMode,
)
from core.schemas.chat import (  # noqa: F401
    ChatMessageRecord,
    ChatMessageType,
    ChatMessagesResponse,
    ChatPhase,
    ChatRespondRequest,
    ChatSessionListResponse,
    ChatSessionSummary,
    ChatStreamAnswerPartEvent,
    ChatStreamDeltaEvent,
    ChatStreamErrorEvent,
    ChatStreamEvent,
    ChatStreamFinalEvent,
    ChatStreamReasoningSummaryEvent,
    ChatStreamStatusEvent,
    ChatStreamTraceEvent,
    ConceptSwitchDecision,
    OnboardingStatusResponse,
    OnboardingSuggestedTopic,
    TutorActivity,
)
from core.schemas.graph import (  # noqa: F401
    GardenerRunResponse,
    GraphConceptDetail,
    GraphConceptDetailResponse,
    GraphConceptListResponse,
    GraphConceptSummary,
    GraphLuckyAdjacentScoreComponents,
    GraphLuckyPickAdjacent,
    GraphLuckyPickWildcard,
    GraphLuckyResponse,
    GraphLuckyWildcardScoreComponents,
    GraphSubgraphEdge,
    GraphSubgraphNode,
    GraphSubgraphResponse,
    LuckyMode,
)
from core.schemas.knowledge_base import (  # noqa: F401
    KBDocumentListResponse,
    KBDocumentSummary,
)
from core.schemas.practice import (  # noqa: F401
    FlashcardRunDetailResponse,
    FlashcardRunListResponse,
    FlashcardRunSummary,
    FlashcardRateRequest,
    FlashcardRateResponse,
    FlashcardSelfRating,
    PracticeFlashcard,
    PracticeFlashcardsResponse,
    StatefulFlashcard,
    StatefulFlashcardsResponse,
)
from core.schemas.quizzes import (  # noqa: F401
    LevelUpPromoteToPracticeResponse,
    LevelUpQuizAttemptSummary,
    LevelUpQuizDetailResponse,
    LevelUpQuizHistoryEntry,
    LevelUpQuizHistoryListResponse,
    LevelUpQuizSubmitResponse,
    MasteryStatus,
    PracticeQuizAttemptSummary,
    PracticeQuizDetailResponse,
    PracticeQuizHistoryEntry,
    PracticeQuizHistoryListResponse,
    PracticeQuizSubmitResponse,
    QuizChoiceSummary,
    QuizCreateResponse,
    QuizFeedbackItem,
    QuizItemResult,
    QuizItemSummary,
    QuizItemType,
)
from core.schemas.research import (  # noqa: F401
    CandidatePromoteRequest,
    CandidatePromotionResponse,
    QueryPlanResponse,
    ResearchCandidateReviewRequest,
    ResearchCandidateSummary,
    ResearchRunSummary,
    ResearchSourceCreate,
    ResearchSourceSummary,
    TopicExecuteRequest,
    TopicPlanRequest,
    TopicProposalResponse,
)

__all__ = [
    "ActionCTA",
    "AnswerParts",
    "AssessmentCard",
    "AssistantDraft",
    "AssistantResponseEnvelope",
    "AssistantResponseKind",
    "CITATION_LABEL_FROM_NOTES",
    "CITATION_LABEL_GENERAL_CONTEXT",
    "ChatMessageRecord",
    "ChatMessageType",
    "ChatMessagesResponse",
    "ChatPhase",
    "ChatRespondRequest",
    "ChatSessionListResponse",
    "ChatSessionSummary",
    "ChatStreamAnswerPartEvent",
    "ChatStreamDeltaEvent",
    "ChatStreamErrorEvent",
    "ChatStreamEvent",
    "ChatStreamFinalEvent",
    "ChatStreamReasoningSummaryEvent",
    "ChatStreamStatusEvent",
    "ChatStreamTraceEvent",
    "Citation",
    "CitationLabel",
    "ConceptSwitchDecision",
    "ConceptSwitchSuggestion",
    "ConversationMeta",
    "EvidenceItem",
    "EvidenceSourceType",
    "FlashcardRateRequest",
    "FlashcardRateResponse",
    "FlashcardRunDetailResponse",
    "FlashcardRunListResponse",
    "FlashcardRunSummary",
    "FlashcardSelfRating",
    "GardenerRunResponse",
    "GenerationTrace",
    "GraphConceptDetail",
    "GraphConceptDetailResponse",
    "GraphConceptListResponse",
    "GraphConceptSummary",
    "GraphLuckyAdjacentScoreComponents",
    "GraphLuckyPickAdjacent",
    "GraphLuckyPickWildcard",
    "GraphLuckyResponse",
    "GraphLuckyWildcardScoreComponents",
    "GraphSubgraphEdge",
    "GraphSubgraphNode",
    "GraphSubgraphResponse",
    "GroundingMode",
    "HierarchyNode",
    "KBDocumentListResponse",
    "KBDocumentSummary",
    "LevelUpPromoteToPracticeResponse",
    "LevelUpQuizAttemptSummary",
    "LevelUpQuizDetailResponse",
    "LevelUpQuizHistoryEntry",
    "LevelUpQuizHistoryListResponse",
    "LevelUpQuizSubmitResponse",
    "LuckyMode",
    "MasteryStatus",
    "OnboardingStatusResponse",
    "OnboardingSuggestedTopic",
    "PracticeQuizAttemptSummary",
    "PracticeQuizDetailResponse",
    "PracticeFlashcard",
    "PracticeFlashcardsResponse",
    "PracticeQuizHistoryEntry",
    "PracticeQuizHistoryListResponse",
    "PracticeQuizSubmitResponse",
    "QuizChoiceSummary",
    "QuizCreateResponse",
    "QuizFeedbackItem",
    "QuizItemResult",
    "QuizItemSummary",
    "QuizItemType",
    "ReadinessSnapshotResponse",
    "ReadinessTopicState",
    "RefusalReason",
    "ResearchCandidateReviewRequest",
    "ResearchCandidateSummary",
    "ResearchRunSummary",
    "ResearchSourceCreate",
    "ResearchSourceSummary",
    "CandidatePromoteRequest",
    "CandidatePromotionResponse",
    "QueryPlanResponse",
    "TopicExecuteRequest",
    "TopicPlanRequest",
    "TopicProposalResponse",
    "ResponseMode",
    "StatefulFlashcard",
    "StatefulFlashcardsResponse",
    "TutorActivity",
]
