"""Typed research planning types (AR5.1).

These are data-only planning outputs for topic discovery, query
planning, and candidate promotion decisions.  They do not own any
execution — the existing runner/service/candidate pipeline handles that.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal


SourceClass = Literal[
    "paper",
    "article",
    "docs",
    "tutorial",
    "expert_post",
    "update",
    "other",
]


@dataclass(frozen=True, slots=True)
class TopicProposal:
    """A proposed study topic or subtopic from a research goal.

    Generated by a topic planner from a high-level research request.
    Must be reviewed/approved before query planning begins.
    """

    topic: str
    subtopics: list[str] = field(default_factory=list)
    source_classes: list[SourceClass] = field(default_factory=list)
    rationale: str = ""
    priority: Literal["high", "medium", "low"] = "medium"

    @property
    def has_subtopics(self) -> bool:
        return len(self.subtopics) > 0


@dataclass(frozen=True, slots=True)
class ResearchQuery:
    """A single search query within a research query plan."""

    query_text: str
    source_class: SourceClass = "other"
    max_results: int = 10


@dataclass(frozen=True, slots=True)
class ResearchQueryPlan:
    """A bounded set of queries generated from an approved topic proposal.

    Results from executing this plan feed into the existing candidate
    queue as pending candidates.
    """

    topic: str
    queries: list[ResearchQuery] = field(default_factory=list)
    max_total_candidates: int = 25
    rationale: str = ""

    @property
    def query_count(self) -> int:
        return len(self.queries)

    @property
    def is_bounded(self) -> bool:
        """True if the plan respects sensible limits."""
        return self.query_count <= 10 and self.max_total_candidates <= 50


PromotionAction = Literal[
    "promote",       # Move to trusted material
    "defer",         # Keep as candidate for later review
    "reject",        # Drop from consideration
    "quiz_gate",     # Require quiz completion before promotion
]


@dataclass(frozen=True, slots=True)
class CandidatePromotionDecision:
    """A decision about whether to promote a research candidate.

    Promotion means the candidate enters the trusted ingest pipeline.
    All decisions require prior user approval of the candidate itself.
    """

    candidate_id: int
    action: PromotionAction
    reason: str = ""
    requires_review_quiz: bool = False

    @property
    def is_promoting(self) -> bool:
        return self.action in ("promote", "quiz_gate")
